# Generated by Django 5.2.5 on 2025-08-19 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
