# Generated by Django 5.2.5 on 2025-08-19 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blogmodel_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authormodel',
            options={'verbose_name_plural': 'Authors'},
        ),
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'verbose_name_plural': 'Blogs'},
        ),
    ]
