# Generated by Django 5.2.5 on 2025-08-19 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_authormodel_options_alter_blogmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='authormodel',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
