# Generated by Django 5.2.5 on 2025-08-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_tag_blogmodel_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image_url',
            field=models.TextField(blank=True, default='', max_length=50),
        ),
    ]
