# Generated by Django 5.2.5 on 2025-08-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blogmodel_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
