# Generated by Django 5.2.5 on 2025-08-22 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_blogmodel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='image_url',
            field=models.ImageField(null=True, upload_to='blog_images'),
        ),
    ]
